"""Standing invariants — SAME definitions run as post-run job task in the workspace
(via retail_lakehouse.audit.invariants) and as integration-marked tests here.
"""

import pytest

pytestmark = [pytest.mark.dq, pytest.mark.integration, pytest.mark.skip(reason="skeleton")]


def test_conservation_per_batch(): ...
def test_exactly_one_current_per_scd2_key(): ...
def test_no_overlapping_version_intervals(): ...
def test_quarantine_rate_below_threshold(): ...
def test_no_future_ingest_ts(): ...
def test_fct_sales_revenue_matches_independent_recompute(): ...
def test_audit_rows_exist_for_every_run(): ...  # R4 canary
