"""Integration tier — thin pytest wrappers over retail_lakehouse.integration.assertions.

The SAME assertion definitions run in-workspace via the integration-assertions entry
point (job.integration_tests); these wrappers exist for local/manual runs and reporting.
No assertion logic in this file — one wrapper per assertions.assert_* function.
"""

import pytest

pytestmark = [pytest.mark.integration, pytest.mark.skip(reason="skeleton — not implemented")]


def test_cold_start_all_objects_exist_conservation_green(): ...
def test_replay_day1_adds_zero_rows_anywhere(): ...
def test_cdc_scd2_matches_library_oracle(): ...  # oracle cross-check (unit §1.4 impl)
def test_poison_day_quarantine_routing_and_reasons(): ...
def test_schema_drift_rescued_warn_fired_pipeline_survives(): ...
def test_drift_gate_threshold_fails_pipeline_as_designed(): ...
def test_late_fact_corrects_old_date_aggregate(): ...
def test_idempotent_rerun_zero_row_deltas(): ...
