"""DQ registry meta-tests — run in CI (local, no workspace).

Coverage cannot silently regress: these tests fail if conf/dq_rules.yml weakens.
"""

import pytest

pytestmark = [pytest.mark.dq, pytest.mark.skip(reason="skeleton — not implemented")]


def test_every_rule_references_real_table_and_column(): ...
def test_every_table_has_minimum_key_null_and_dup_rules(): ...
def test_severity_values_valid_and_thresholds_in_range(): ...
def test_no_gate_rules_on_observe_tier_activity(): ...
def test_no_warn_only_rules_on_order_event_keys(): ...
