"""Unit spec §1.3 — CDC normalization + op-aware validation."""

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.skip(reason="skeleton — not implemented")]


def test_snapshot_rows_become_synthetic_upserts(): ...
def test_both_branches_produce_identical_schema(): ...
def test_delete_with_null_payload_not_flagged(): ...
def test_null_change_ts_quarantined_regardless_of_op(): ...
def test_orphan_delete_tagged_and_held_not_dropped(): ...
