"""Unit spec §1.2 — keyed deduplication."""

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.skip(reason="skeleton — not implemented")]


def test_exact_duplicates_collapsed(): ...
def test_same_key_keeps_latest_by_sequence_payload_checked(): ...
def test_equal_sequence_uses_documented_tiebreaker(): ...
def test_stable_under_input_shuffle(): ...
def test_empty_and_single_row_pass_through(): ...
