"""Unit spec §1.4 — hand-rolled SCD2 (the oracle). These tests define correct SCD2
semantics; integration cross-checks auto_cdc_flow output against this implementation."""

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.skip(reason="skeleton — not implemented")]


def test_change_closes_old_version_opens_new(): ...
def test_identical_resend_adds_zero_rows(): ...
def test_late_event_resequences_history_correctly(): ...
def test_exactly_one_current_per_key(): ...
def test_intervals_contiguous_and_non_overlapping(): ...
def test_effective_dates_from_sequence_never_processing_time(): ...
def test_composite_keys_never_cross_match(): ...
