"""Unit spec §1.1 — revenue calculation (lifecycle + FX + line revenue)."""

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.skip(reason="skeleton — not implemented")]


def test_paid_order_included_in_revenue(): ...
def test_cancelled_order_excluded(): ...
def test_placed_only_order_excluded(): ...
def test_fx_normalization_applied_once_original_retained(): ...
def test_cancelled_before_placed_resolves_terminal(): ...
def test_total_revenue_exact_decimal(): ...
def test_idempotent_on_same_input(): ...
