"""Unit spec §1.6 — aggregations, funnel, and the closure-bug regression test."""

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.skip(reason="skeleton — not implemented")]


def test_conservation_sum_aggregate_equals_sum_input(): ...
def test_null_dimension_goes_to_unknown_bucket(): ...
def test_group_count_exact(): ...
def test_factory_generated_functions_filter_own_segment(): ...
def test_factory_outputs_differ_between_segments(): ...  # the closure-bug regression
def test_funnel_attribution_window_boundary(): ...
