"""Unit spec §1.5 — batch scoping, filename parsing, lateness-window classification."""

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.skip(reason="skeleton — not implemented")]


def test_valid_filename_parses_batch_metadata(): ...
def test_malformed_filename_yields_sentinel_never_raises(): ...
def test_late_event_inside_window_marked_in_window(): ...
def test_late_event_beyond_window_flagged_not_dropped(): ...
def test_exact_window_boundary_per_adr(): ...
